Add refresh session msg for search extension
ghostery/ghostery-extension pull request #1066
Opened 2023-03-13 13:46 UTC by smalluban

Fixes #1010

2023-03-16 15:24 UTC, chrmod requested changes
lets share this code with the MV2 as we know that the that code is incorrectly scoped to ghostery browser only

2023-03-17 12:44 UTC, chrmod requested changes
the abstraction in MV2 could be removed but if you don't see an opportunity in code sharing then at least lets remove the incorrect if statement in the MV2 in this PR

2023-03-17 14:37 UTC, philipp-classen commented on extension-manifest-v3/src/background/external.js
> +            session().then(
Can't the "session()" call fail?

2023-03-17 14:38 UTC, philipp-classen approved these changes

2023-03-20 08:36 UTC, chrmod approved these changes

2023-03-20 08:37 UTC, merged