POC: Contextual Onboarding
ghostery/ghostery-extension pull request #1079
Opened 2023-03-21 15:41 UTC by chrmod

2023-03-21 15:53 UTC, smalluban requested changes
Generally, I think we could use `ui/onboarding` module, and extend it with a new component - so you would avoid a lot of copy & paste.

2023-03-21 15:53 UTC, smalluban commented on extension-manifest-v3/src/background/index.js
> +import './contextual-conboarding';
no extension

2023-03-21 15:53 UTC, smalluban commented on extension-manifest-v3/src/content_scripts/contextual-onboarding.js
> +import { showIframe } from '@ghostery/ui/contextual-onboarding/iframe';
No copyrights

2023-03-21 15:53 UTC, smalluban commented on extension-manifest-v3/src/background/contextual-conboarding.js
> +function openIframe(tabId) {
I would use `src/background/onboarding.js`, and add this there. It is the same feature, but only another representation - no need to a new file here.

2023-03-21 15:53 UTC, smalluban commented on extension-manifest-v3/src/manifest.chromium.json
> +      "run_at": "document_start",
It might be `document_idle` as it does not have to be "super fast".

2023-03-21 15:53 UTC, smalluban commented on extension-manifest-v3/src/store/stats.js
> +      const tabId = await chrome.runtime.sendMessage({
The `getCurrentTabId` was here only for the fallback for the Firefox iframe limitation. Is using the `chrome.tabs` API not preferred where possible?

2023-03-22 12:19 UTC, chrmod commented on ui/src/modules/onboarding/iframe.js
> +        all: initial !important;
@smalluban please take a look on this. some pages have styles that are as broad as `div`. Eg. example.com

2023-04-12 07:35 UTC, smalluban commented
Alredy done in #1104

2023-04-12 07:35 UTC, closed without merging