MV3: fix reporing startup race
ghostery/ghostery-extension pull request #1147
Opened 2023-04-28 15:04 UTC by chrmod

2023-05-11 09:51 UTC, smalluban requested changes
Generally, this solution only adds a feature to switch the result of the setup process, so it is mutable (not like in #1152, where once finished, the promise is cleared).

However, it does not help with the reporting much, as we could simply check `reporting.isActive` as before. When `terms` go to `false` (which is only possible by dev tools, which clears out the options), observe method can just call `reporting.unload()` - which is sync operation by the way.

I can't see here a case, which cannot be covered with #1152

2023-05-11 09:51 UTC, smalluban commented on extension-manifest-v3/src/background/utils/startup-guard.js
> +export default (starter, stopper) => {
If you want to have the option to abort a "pending" promise, we can use the `AbortController` API, as it is already widely supported: https://caniuse.com/abortcontroller (including Safari, which is our main target currently).

2023-05-11 09:51 UTC, smalluban commented on extension-manifest-v3/src/background/utils/startup-guard.js
> +export default (starter, stopper) => {
Please use the `function` statement in modules where possible (if you don't set `const something = () => {}`. Also, the copyright missing.

2023-05-12 10:10 UTC, chrmod commented
fixed by https://github.com/ghostery/ghostery-extension/pull/1152

2023-05-12 10:10 UTC, closed without merging