Safari: fix DNR rules
ghostery/ghostery-extension pull request #1254
Opened 2023-08-11 14:26 UTC by chrmod

2023-08-11 14:47 UTC, philipp-classen submitted a review, later dismissed

2023-08-11 14:52 UTC, smalluban requested changes
I am sure that logging was quite helpful when debugging, but I am not sure if we should leave it there, as the second argument of the `getCompatRule()` is never used. At least, I would add a way to call the command like this `npm run download-engines --debug` or something similar.

2023-08-11 14:52 UTC, smalluban commented on extension-manifest-v3/scripts/download-engines/utils.js
> +  if (!newRule.condition.urlFilter && !newRule.condition.regexFilter) {
The logic didn't change from the previous revision, only you added a log message. Is this gives us anything?

2023-08-14 07:24 UTC, smalluban approved these changes
I have added `--debug` mode, so it can stay as it is for now.

2023-08-14 07:26 UTC, merged