DNR feedback on Safari
ghostery/ghostery-extension pull request #1583
Opened 2024-05-09 13:29 UTC by smalluban

2024-05-10 09:19 UTC, smalluban commented
@chrmod Please reset to the new version of the branch if you want to work on this branch. I made a rebase to the current `main`.

2024-05-10 10:35 UTC, chrmod requested changes

2024-05-10 10:35 UTC, chrmod commented on extension-manifest-v3/src/background/stats.js
> +                if (request.url === info.request.url) {
this is great

please make it even better and add update stats for all urls that haven't matched already observed urls

2024-05-10 10:37 UTC, philipp-classen approved these changes
Tested the refactoring with Chrome (reporting still works).

2024-05-13 12:02 UTC, philipp-classen commented
To fix the merge conflict: this is what has been added
https://github.com/ghostery/ghostery-extension/commit/9e9f9620de3ab1483aa7f09e5f8efb8768b81c86

2024-05-14 11:42 UTC, smalluban commented
@philipp-classen I Added config for Edge, please scan if it is right now - https://github.com/ghostery/ghostery-extension/pull/1583/files#diff-0077760dac31d77155faff549d98ea292441ec2f4f177fdd0ceee1d7620e4899R72

2024-05-14 16:45 UTC, philipp-classen submitted a review, later dismissed

2024-05-14 16:45 UTC, philipp-classen commented
> @philipp-classen I Added config for Edge, please scan if it is right now - https://github.com/ghostery/ghostery-extension/pull/1583/files#diff-0077760dac31d77155faff549d98ea292441ec2f4f177fdd0ceee1d7620e4899R72

Looks good!

2024-05-15 12:06 UTC, smalluban commented
@chrmod I think I made it as close to a 100% match as possible. The `getMatchedRules` must take a timestamp, as without it, it will return blocked requests for the previous page in the same tab. 

Safari has a known bug, that if you pass the URL directly in the new tab (add tab and write URL) - then the `onBeforeNavigate` event is not triggered. Then, we use a message from the content script to set up stats. In this case and only, the timestamp will be "too late" - so some of the DNR feedback might be cut off.

@chrmod Please re-review.

2024-05-16 08:28 UTC, chrmod approved these changes

2024-05-16 08:31 UTC, merged