Release v10.3.5
ghostery/ghostery-extension pull request #1634
Opened 2024-06-05 09:16 UTC by smalluban

2bd7b1e53545341829fc6679b9c6673ccbf56f87 (origin/main, origin/HEAD, main) Update dependencies (#1633)
c8772ac93dfb9bfcfbb51e7eeb5340a264c82fb3 Fix Safari open settings page from another context (#1632)
71ab659038a70f64a3d0bc40958da32d81fe5d30 Lift country restrictions with the Chrome migration. (#1631)
286d138c27d502005edba46639ecc0da20151eb3 Clean up devtools mode (#1628)
d60f79eaf48ea2852d48c2c18b75b74aa2c95e85 Use frame URL to prevent from using anti-tracking (#1630)
9e115302da723408d48fdb61521a4f103a068b9d Fix close Opera SERP popup actions after reloading extension (#1629)

2024-06-05 10:09 UTC, chrmod requested changes
TODO: improve vocabulary for Trusting sites

2024-06-06 10:43 UTC, chrmod approved these changes

2024-06-06 10:44 UTC, philipp-classen approved these changes

2024-06-06 10:53 UTC, GRadziejewski approved these changes
Tests results for Chrome, Edge, Opera and Firefox are here: https://github.com/ghostery/ghostery-extension/issues/1636#issuecomment-2149451537

2024-06-06 10:54 UTC, merged