Ghostery 10: Firefox scriptlet injection
ghostery/ghostery-extension pull request #1790
Opened 2024-08-07 12:41 UTC by chrmod

Injecting blobs allow scriptlets to by pass CSP. This technique was already in use in Ghostery 8 and with autoconsent.

2024-08-07 12:48 UTC, smalluban requested changes

2024-08-07 12:48 UTC, smalluban commented on extension-manifest-v3/src/background/adblocker.js
> +    if (navigator.userAgent.includes('Firefox')) {
I think this is place to use `__PLATFORM__`

```suggestion
    if (__PLATFORM__ === 'firefox') {
```

2024-08-07 13:02 UTC, smalluban commented
This is critical path for extension. Please test it before merging @GRadziejewski

2024-08-07 13:02 UTC, smalluban reviewed
LGTM.

2024-08-07 13:03 UTC, smalluban approved these changes

2024-08-09 16:21 UTC, chrmod commented
It looks like blob injection is not needed when `chrome.scripting.executeScript` is in use.

2024-08-09 16:21 UTC, closed without merging