Move @ghostery/libs to extension
ghostery/ghostery-extension pull request #1841
Opened 2024-08-26 15:32 UTC by chrmod

2024-08-26 18:43 UTC, philipp-classen approved these changes

2024-08-27 06:07 UTC, smalluban requested changes

2024-08-27 06:07 UTC, smalluban commented on extension-manifest-v3/src/background/telemetry/metrics.js
>  import browser from 'webextension-polyfill';
Please remove `webextension-polyfill` from dependencies.

2024-08-27 09:28 UTC, smalluban approved these changes

2024-08-27 14:42 UTC, merged