feat(options): Add support for managed storage
ghostery/ghostery-extension pull request #2015
Opened 2024-10-30 14:52 UTC by smalluban

2024-10-30 15:56 UTC, chrmod requested changes
we need one more option to `disablePause` from the panel

2024-10-30 15:56 UTC, chrmod commented on src/pages/onboarding/index.js
> +  }
not needed

2024-10-30 15:56 UTC, chrmod commented on src/store/managed-options.js
> +  disableUserSettings: false,
`disableSettings`

2024-10-30 15:56 UTC, chrmod commented on src/store/managed-options.js
> +  enableTerms: false,
`disableOnboarding`

2024-10-30 16:09 UTC, smalluban commented on src/store/options.js
> +        ? applyManagedOptions(options)
No: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed#browser_compatibility

2024-10-31 09:22 UTC, smalluban commented
The Chrome schema has been added. Here you have docs about configuration it in different platforms:
https://www.chromium.org/administrators/configuring-policy-for-extensions

2024-10-31 11:00 UTC, philipp-classen commented
For Chromium on Linux (tested on Arch):

Create a file /etc/chromium/policies/managed/test_policy.json (assumption: extension ID = "gjdacaklflccploihbcnabmhffhcbljm")

```
{
  "3rdparty": {
    "extensions": {
      "gjdacaklflccploihbcnabmhffhcbljm": {
        "disableOnboarding": true,
        "disableUserControl": true,
        "trustedDomains": ["bbc.com"]
      }
     }
   }
 }
```

chrome://policy/ shows
![policy](https://github.com/user-attachments/assets/8ce2ed83-9a55-4c82-8523-d50d06e6e781)

2024-11-04 14:05 UTC, chrmod approved these changes

2024-11-04 14:06 UTC, merged