fix(telemetry): remove obsolete parameters
ghostery/ghostery-extension pull request #2135
Opened 2024-12-10 13:18 UTC by smalluban

Clears out static (hardcoded) and unused parameters.

2024-12-10 13:28 UTC, philipp-classen approved these changes

2024-12-10 13:43 UTC, chrmod requested changes
please remove the `_getSearchExtensionMetrics` method as well

2024-12-10 14:04 UTC, smalluban commented on src/background/telemetry/metrics.js
> +    this._sendReq('active', ['daily', 'weekly', 'monthly']);
The `_sendReq` checks each frequency if the time expired... So I cleaned this up to match L386

2024-12-11 11:04 UTC, chrmod approved these changes

2024-12-11 11:08 UTC, merged