Release 8.7.0
ghostery/ghostery-extension pull request #765
Opened 2022-04-11 07:30 UTC by smalluban

2022-04-13 12:43 UTC, chrmod requested changes

2022-04-13 12:43 UTC, chrmod commented on package.json
> +  "version": "8.6.3",
lets not change the version here, no need to bump it as we never publish

2022-04-13 12:50 UTC, philipp-classen approved these changes

2022-04-14 10:35 UTC, chrmod approved these changes

2022-04-14 10:35 UTC, merged